### ISSUE TITLE
Make List implements IEnumerable

### ISSUE THREAD

**Issue by KubaSzostak** [isc30/linq-collections#42]
The same way like in C#.

**Comment by isc30** [comment]
Due to some technical limitations of ES5 (no native `[Symbol.Iterator]` for example) the library introduces its own iteration methods. When you use a Query method (Select, Where, etc) in a collection, it returns you a **queryable iterator with the collection binded**. The collection itself cannot be iterated.

You can get the basic iterator for the given collection by calling `myCollection.asEnumerable()`

I hope this helps, feel free to expose your use-case if you have a better solution in mind.
Thanks a lot for the contribution.
